/**
 * Created by U1SA14 on 2/22/2017.
 */
var regex = /(?=\d\d[.]\d\d|\d\d\d[.]\d\d)([^\s]+)/gi;
var str = 'Note: Nemucod JavaScript Downloader DNS Request(s): evergladesit[.]com (50.63.215[.]1) coachnwillies[.]com (184.168.172[.]1) mapoftexas[.]net (184.168.137[.]1) modlowe[.]com (97.74.55[.]128) haroldsowls[.]com (184.168.156[.]1) netmix360[.]com (50.63.78[.]1) spiceoflifecuisine[.]com (50.62.238[.]138) HTTP Request(s): hxxp://evergladesit[.]com/counter/?TXeYC' +
    '(qidc.cossette[.]com [209.171.113[.]253]) X-PHP-Originating-Script:' +
    'Ua6ZYzS1 Note: Kovter Click Fraud Trojan TCP Activity: 23.77.152[.]183 77.55.171[.]89 45.244.4[.]216 89.47.20[.]179 --------------------------------';
//var m;
var artifacts = [];
var regex_ip = [];
var ip;
var tmp = [];
var meh = 0;
var i = 0;

// Regex Query for parsing malicious ip addresses and adding them as artifacts
while ((ip = regex.exec(str)) != null) {
    if (ip.index == regex.lastIndex) {
        regex.lastIndex++;
    }
    tmp.push(ip[0].split());
    tmp[i] = tmp[i].toString().replace(/\[|\]|\(|\)/gi, "");
    i++;
}
uniqueIp  = tmp.filter(function(elem, pos) {
    return tmp.indexOf(elem) == pos;
});
for (i=0; i<uniqueIp.length;i++){
    artifacts.push({'type': 'IP Address', 'value': uniqueIp[i].toString(), 'description': 'Generated by IRHub_Mail Parser', 'inc_id': 'Test'});
    console.log(artifacts[i]);
}
uniqueIp = [];
tmp = [];
i = 0;
//m = '[CyberIntel Confidential] Driveby redinoversum[.]blogspot[.]com'
var m = new String;
m = 'CYI1 - Informational: (UPDATE 2) Member Submission: "The Office of The State Attorney Complaint" - Phishing E-mails [FS-ISAC Amber]'
console.log(m);
q = m.replace(/re: |\[CyberIntel Confidential\]\s|CY\w\d(\:|\s\-\s)|Wapack\sLabs\sReport\:\s|Informational\:\sMember\sSubmission\:\s|Aviation\sISAC\:\s|Informational\:\s\(UPDATE\s\d\)\sMember\sSubmission\:\s|\[FS-ISAC\s\w+\]/gi, "");
console.log(q);



//console.log(m);
var n;
var z;
o = m;

var test = [/re:\s/gi, /\[CyberIntel Confidential\]\s/gi, /CY\w\d(\:|\s\-\s)/gi, /Wapack\sLabs\sReport\:\s/gi, /Informational\:\sMember\sSubmission\:\s/gi, /Aviation\sISAC\:\s/gi, /Informational\:\s\(UPDATE\s\d\)\sMember\sSubmission\:\s/gi, /\[FS-ISAC\s\w+\]/gi];

var test1 = /CYI1/gi;

for (i=0; i<test.length;i++){
    console.log(test[i]);
   // z = test[i];
   // console.log(z);
   // n = m.replace(z, "");
   // console.log(n);
    m = m.replace(test[i].valueOf(), "");
    console.log(m);
}

o = m.replace("Re: ", "").replace("[CyberIntel Confidential] ","").replace("CYI1 - Informational: Member Submission: ","").replace("CYT3: Member Submission: ","").replace("CYI1 - Informational: (UPDATE 2) Member Submission: ","").replace("ANC3: ","").replace("NCCIC / US-CERT:","").replace("[FS-ISAC Red]","").replace("[FS-ISAC Amber]","").replace("[FS-ISAC Green]","").replace("[FS-ISAC White]","");
console.log("Hello this is O");
console.log(o);
p = m.replace(test1, "");
console.log(p);

var moo = "COI: FS-ISAC Daily Report - February 28, 2017 [FS-ISAC Amber]"
if (moo.search("COI: FS-ISAC Daily Report") == -1) {
    console.log("hello");
}
function getHostName(url) {
    var match = url.match(/:\/\/(www[0-9]?\.)?(.[^/:]+)/i);
    if (match != null && match.length > 2 && typeof match[2] === 'string' && match[2].length > 0) {
        return match[2];
    }
    else {
        return null;
    }
}
console.log(getHostName('woofs://mail.google.co.uk'));
